### ISSUE TITLE
slow growers

### ISSUE THREAD

**Issue by 8blues** [jlw-ecoevo/gRodon#1]
Hi,

Thank you very much for developing this excellent tool.

I am particular interested in the slow growers. I generate MAGs and I found that a majority of my MAGs have minimum doubling time > 5 hours (mostly between 5 to 30), but it seems that your tool might largely underestimate the minimum doubling time if it is > 5 hours. Is it still appropriate to compare the minimum doubling time among my MAGs? The tool might underestimate, but maybe the predicted minimum doubling time is still comparable among slow-growing MAGs? 

I am trying to link the MAG growth rate to their distribution pattern. It is impossible to do the analyses if I only report all my MAGs have > 5 hours. Or do you have a better idea to compare the minimum doubling time among slow growers?

**Comment by jlw-ecoevo** [comment]
I wish I had a better answer for you here, but the best I can do is say "maybe". If you look at figure 1a in the preprint it looks like there is still a positive correlation between gRodon predictions and growth rate - which would imply you can still make relative comparisons between organisms as you suggest. That being said, figure 1b suggests that after about 5hrs any selection on growth rate is so small as to be overcome by drift - meaning that variation in predicted values between strains would be mostly due to noise - making comparisons above this threshold essentially meaningless. So, you can try, but I wouldn't expect very strong patterns, and the absence of a pattern in predicted growth rates doesn't necessarily mean the differences don't exist. Data that isn't on the preprint but that may end up in the final published paper suggests that selection on codon usage in organisms with d>5hr is much lower than in organisms with d<5hr.

Predicting growth rate in slow growers is largely an unsolved problem - one I am still interested in. Unfortunately, I don't have a better approach to offer at this time.

**Comment by 8blues** [comment]
Thank you for the prompt reply. Yes, it would be great to predict the growth rate of slow growers because we would have a continuous measure instead of a categorical classification (i.e., d > 5 and d < 5), but I understand the difficulty in predicting the growth rates of slow growers.

I am looking forward to seeing the final publication.
