### ISSUE TITLE
metagenome mode for MAG?

### ISSUE THREAD

**Issue by 8blues** [jlw-ecoevo/gRodon#2]
Hi,

Does it make sense if I use metagenome mode for MAGs? The results I obtain from metagenome mode is in line with my expectations because the MAGs with longer doubling time tend to be dominant in nutrient-poor samples. 

However, I found the results from metagenome mode is inversely related to the results from partial mode (see the figure attached). In the preprint and  vignette you seem to prefer using partial mode for MAGs?
[Rplot01.pdf](https://github.com/jlw-ecoevo/gRodon/files/5907890/Rplot01.pdf)

**Comment by jlw-ecoevo** [comment]
Yes, using metagenome mode should work fine but you may lose out a little bit on accuracy.  

That is a very interesting pattern. Note that for the few MAGs with d<5 the two modes seem to more or less agree - it seems that where they differ is mostly among the slow growers where gRodon's results are generally less reliable (as we discussed in a previous thread). 

The difference between "partial" and "metagenome" mode is that metagenome mode only takes into account the degree of bias in the highly expressed genes, whereas partial mode also takes into account whether those highly expressed genes have the same bias. It looks like the slow growers in your sample may be hitting a floor on bias - for things to have a similar bias they must be biased in the first place. I can't say for sure that is what is going on but it is my best guess. You might also get bad results with partial mode if your MAGs have any contamination (because the contaminating organism may have a different bias). I wonder also if the nature of MAGs themselves make partial mode a somewhat less reliable candidate, since they are clustered by GC content and sequence-co-occurrence and may represent a collection of closely related strains with somewhat different codon biases. 

In any case, if you have any doubt about contamination you should try metagenome mode, and in general metagenome mode is a perfectly ok choice. I'll have to do some follow up with this in the tutorial when I get a chance.
